[2024-08-28 09:23:23,454](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e98e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 09:23:23,455](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A01%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63786220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 09:23:23,455](run_ledsrv) Ошибка Табло: возможно нет связи? [Errno 101] Network is unreachable. 
[2024-08-28 09:23:27,912](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A02 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63786e20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 09:23:27,913](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A02%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790610>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 09:23:27,913](run_ledsrv) Ошибка Табло: возможно нет связи? [Errno 101] Network is unreachable. 
[2024-08-28 12:03:31,099](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637c3d30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:03:31,216](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e9a00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:03:33,233](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:11:12,792](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790a30>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:11:12,794](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:11:14,796](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:13:02,385](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379ddf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:13:02,387](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:13:04,388](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:15:59,759](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637c3fd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:15:59,761](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63786790>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:16:01,763](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:16:21,524](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:16:21,525](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a85e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:16:23,527](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:18:26,431](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637864f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:18:26,432](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637c3ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:18:28,435](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:18:30,245](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e98e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:18:30,246](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790040>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:18:32,249](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:18:39,873](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:18:39,875](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379daf0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:18:41,877](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:19:47,479](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790cd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:19:47,483](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e92b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:19:49,485](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:20:33,748](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d9d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:33,750](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d100>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:35,752](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:20:37,540](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63786f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:37,542](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63a78910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:39,544](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:20:42,818](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63a78520>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:42,819](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A03%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63786730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:44,822](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:20:47,131](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d760>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:47,132](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A04%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e90d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:20:49,134](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:39:10,087](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a89a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:39:10,088](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A04%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637908b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:39:12,090](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:44:21,668](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637af220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:44:21,669](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A04%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379dc70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:44:23,670](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:44:45,058](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A04 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8b80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:44:45,059](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A04%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a80d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:44:47,062](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:45:11,832](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637c3f70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:11,834](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A05%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e9fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:13,836](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:45:14,482](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A06 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637af670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:14,484](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A06%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8130>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:16,486](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:45:17,098](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A07 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8e50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:17,100](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A07%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d3a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:19,102](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:45:19,656](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A08 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:19,684](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A08%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:21,687](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:45:22,198](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A09 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637af220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:22,200](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A09%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:24,202](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:45:24,798](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A010 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e9d00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:24,801](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A010%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a81c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:45:26,803](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:46:12,452](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8730>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:46:12,454](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A011%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637af400>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:46:14,456](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:47:35,681](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A011 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637b3340>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:47:35,708](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A011%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8850>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:47:37,710](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:47:58,794](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:47:58,795](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A012%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d3a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:48:00,798](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:48:04,740](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379dd60>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:48:04,742](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A012%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637b31c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:48:06,744](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 12:48:07,957](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790220>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:48:07,958](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A012%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379da00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 12:48:09,961](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:00:59,261](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A012 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8c70>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:00:59,262](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A012%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:01:01,264](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:01:05,411](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637c3fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:01:05,413](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637afcd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:01:07,416](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:02:14,488](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637afbb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:02:14,490](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8b80>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:02:16,492](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:03:06,672](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a82b0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:03:06,673](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d070>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:03:08,675](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:03:10,360](tmove) {"stdout": null, "stderr": "\u041e\u0448\u0438\u0431\u043a\u0430: \u0432 \u0437\u0430\u043f\u0440\u043e\u0441\u0435 \u043e\u0441\u0442\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0447\u0435\u0435 \u043c\u0435\u0441\u0442\u043e, \u043d\u043e\u043c\u0435\u0440 \u043e\u0447\u0435\u0440\u0435\u0434\u0438 \u0438\u043b\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u0441\u0434\u0432\u0438\u0433\u0430. "}
[2024-08-28 13:03:49,460](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d550>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:03:49,462](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637900a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:03:51,465](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:05:40,704](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637b3f10>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:05:40,705](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d6a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:05:42,707](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:05:54,731](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e99d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:05:54,732](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8670>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:05:56,735](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:06:11,863](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63a78460>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:06:11,865](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637af940>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:06:13,866](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:06:22,482](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637b31f0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:06:22,484](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a80a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:06:24,486](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:06:26,833](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8fa0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:06:26,836](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A014%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e9cd0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:06:28,838](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:08:18,742](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d8e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:08:18,744](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A014%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d63790b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:08:20,746](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:08:30,447](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637b3eb0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:08:30,449](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A015%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d250>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:08:32,451](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:08:43,866](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e9160>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:08:43,869](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A015%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8b50>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:08:45,871](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:09:42,255](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637c3be0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:09:42,256](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A015%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637b36a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:09:44,258](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:11:23,533](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A016 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637b3820>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:11:23,535](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A016%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a85e0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:11:25,537](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:11:37,782](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8640>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:11:37,785](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d9d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:11:39,787](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:13:46,809](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A013 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379d190>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:13:46,811](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A013%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a1b20>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:13:48,813](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:13:55,178](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A015 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379df40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:13:55,180](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A015%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d6379da00>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:13:57,182](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:24:19,425](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A017 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a8a90>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:24:19,427](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A017%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a89a0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:24:21,429](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:24:24,076](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A017 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a1ac0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:24:24,077](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A017%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a1910>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:24:26,080](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 13:24:30,433](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A018 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637c3ee0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:24:30,435](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A018%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a87c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 13:24:32,437](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2024-08-28 14:27:21,372](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=1&t=%D0%A019 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637e91c0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 14:27:21,431](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A019%2Cokno_nomer%2C1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d637a10d0>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2024-08-28 14:27:21,437](run_ledsrv) Ошибка Табло: возможно нет связи? [Errno 101] Network is unreachable. 
