[2025-02-08 11:34:40,348](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f039f126370>: Failed to establish a new connection: [Errno 111] Connection refused')). 
[2025-02-08 11:34:50,072](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=---- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f039f126f40>: Failed to establish a new connection: [Errno 111] Connection refused')). 
