[2025-04-16 16:21:51,678](main) Filepid(srv13.pid) exists, but the process is not started! Delete filepid
[2025-04-16 16:28:06,875](main) Filepid(srv13.pid) exists, but the process is not started! Delete filepid
[2025-04-16 16:30:38,811](main) Filepid(srv13.pid) exists, but the process is not started! Delete filepid
[2025-04-16 16:37:40,236](main) Filepid(srv13.pid) exists, but the process is not started! Delete filepid
[2025-04-16 17:06:50,062](main) Filepid(srv13.pid) exists, but the process is not started! Delete filepid
[2025-04-16 17:08:38,773](get_queues) {"stdout": {"1": {"name": "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u0443\u0440\u0430", "shortname": "\u0420\u0435\u0433\u0438\u0441\u0442\u0440", "prefix": "\u0420", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "2": {"name": "\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u0443\u0440\u0430 \u043f\u043e \u043b\u044c\u0433\u043e\u0442\u0435", "shortname": "\u041b\u044c\u0433\u043e\u0442\u043d.", "prefix": "\u041b", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "3": {"name": "\u0421\u0442\u043e\u043c\u0430\u0442\u043e\u043b\u043e\u0433\u0438\u044f", "shortname": "\u0421\u0442\u043e\u043c\u0430\u0442.", "prefix": "\u0421", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "4": {"name": "\u041a\u0440\u043e\u0432\u043e\u0441\u0434\u0430\u0447\u0430", "shortname": "\u041a\u0440\u043e\u0432.", "prefix": "\u041a", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "5": {"name": "\u0414\u0435\u0436\u0443\u0440\u043d\u044b\u0439 (\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0442\u0443\u0440\u0430)", "shortname": "\u0414\u0435\u0436.", "prefix": "\u0414", "schedule": {"week": {"0": ["00:00:01", "23:59:59"], "1": ["00:00:01", "23:59:59"], "2": ["00:00:01", "23:59:59"], "3": ["00:00:01", "23:59:59"], "4": ["00:00:01", "23:59:59"], "5": ["00:00:01", "23:59:59"], "6": ["00:00:01", "23:59:59"]}}}, "6": {"name": "\u041e\u0442\u043b\u043e\u0436\u0435\u043d\u043d\u044b\u0435 6", "shortname": "\u2764 \u041e\u0442\u043b\u043e\u0436.", "prefix": ""}, "7": {"name": "\u041e\u0442\u043b\u043e\u0436\u0435\u043d\u043d\u044b\u0435 7", "shortname": "\u2764 \u041e\u0442\u043b\u043e\u0436.", "prefix": ""}, "8": {"name": "\u041e\u0442\u043b\u043e\u0436\u0435\u043d\u043d\u044b\u0435 8", "shortname": "\u2764 \u041e\u0442\u043b\u043e\u0436.", "prefix": ""}}, "stderr": null}
[2025-04-16 18:09:06,782](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=6&t=S1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F4BD4BF880>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:09:08,782](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2CS1%2Cokno_nomer%2C1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F4BD4DB3D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:09:10,798](run_ledsrv) Ошибка Табло: возможно нет связи? timed out. 
[2025-04-16 18:12:18,416](main) Filepid(srv13.pid) exists, but the process is not started! Delete filepid
[2025-04-16 18:13:05,357](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000183093DDB80>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:13:07,369](run_ausrv) Ошибка Аудиосервера: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32105): Max retries exceeded with url: /talon_nomer%2C%D0%A02%2Cokno_nomer%2C3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000183093F86A0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:16:36,971](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000183093F8AC0>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:18:36,194](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001830940A880>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:20:51,919](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001830941A670>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:21:24,708](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001830940A100>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
[2025-04-16 18:54:53,722](run_tvsrv) Ошибка Инфотабло: возможно нет связи? HTTPConnectionPool(host='127.0.0.1', port=32109): Max retries exceeded with url: /ticket?p=8&t=%D0%A02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000183093DD520>, 'Connection to 127.0.0.1 timed out. (connect timeout=2)')). 
